MyHomepage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [

    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"
# 주소 접근을 쉽게 하기 위한 app_name 불필요하게 중복 해주는 것이 아니다. 아래처럼 나중에 활용 가능
"accountapp:hello_world"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # Login 뷰와 Logout 뷰는 장고에서 제공해준다.

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    #pk 라는 이름의 int 정보를 받겠다 라는 의미
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),


]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.

class Article(models.Model):
    writer=models.ForeignKey(User,on_delete=models.SET_NULL,related_name='article',null=True)
    project=models.ForeignKey(Project,on_delete=models.SET_NULL,related_name='article',null=True)



    #writer=models.ForeignKey(User,on_delete=models.SET_NULL,related_name='article',null=True)
    # on_delete = models.SET_NULL 은 Article이 회원 탈퇴를 했을때 게시글이 사라지지 않고, 알 수 없음으로 주인없는 게시글이 되는걸로 설정한 것
    # article 이라는 이름으로 설정한 이유는 User에서 접근할 때 article이라고 하며 접근하는 것이 자연스럽다고 생각
    # SET_NULL로 설정을 앞에서 해줬기 때문에 null이 가능하도록 True값으로 설정

    title=models.CharField(max_length=200,null=True)
    image=models.ImageField(upload_to='article/',null=False) #False를 통해 이미지를 항상 넣도록 한다.
    content=models.TextField(null=True) # 좀더 긴 글을 적을 필요가 있으므로 CharField 보다는 TextField를 적용하였다.

    created_at = models.DateField(auto_now_add=True,null=True)
    # 언제 만들어 졌는지에 대한 정보 관련 코드, 자동 생성시에도 값이 저장되도록 하는 auto_created

    # 수정 : auto_new_add 로 변경하였는데 그 이유는 정상적으로 데이터가 쌓이게 되는 것이다.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args,**kwargs):
        super().__init__(*args,**kwargs)

    # 여기 까지는 AccountUpdateForm 과 UserCreationForm 은 같은 기능을 한다고 할 수 있다.

        self.fields['username'].disabled = True
        # 이 구문이 추가됨으로서 username의 칸을 비활성화 시켜주는 코드이다.
        # 원치 않게 username을 변경하였다 하더라도 True인 이상 서버에 그 값이 반영되지는 않는다.

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render


# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from articleapp.models import Article

has_ownership=[account_ownership_required, login_required] # decorator들의 배열 생성 (아래에서 처럼 간략화 하기 위함)


class AccountCreateView(CreateView): #CreateView를 상속 받는 클래스
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    template_name = 'accountapp/detail.html'
    context_object_name = 'target_user'
    # CreateView는 뭔가를 만들어야 되니까 form 이랑 성공시 리다이렉트 할 주소를 정해준 반면
    # DetailView는 어떤 모델을 쓰고 모델 내부의 정보를 어떻게 시각화 할지를 신경을 써줘면 된다.

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView,self).get_context_data(object_list=object_list,**kwargs)



    """def get(self,*args,**kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args,**kwargs)
        else:
            return HttpResponseForbidden()

    def post(self,*args,**kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().post(*args,**kwargs)
        else:
            return HttpResponseForbidden()"""
        
        # 데코레이터 전의 함수(메소드) get,post이다.



@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User #장고에서 기본 제공해주는 유저
    #form_class = UserCreationForm
    form_class = AccountUpdateForm
    context_object_name = 'target_user' # 모델의 별명 (User의 별명)
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'



#@method_decorator(login_required, 'get')
#@method_decorator(login_required, 'post')
#@method_decorator(account_ownership_required, 'get')
#@method_decorator(account_ownership_required, 'post')  이 코드들이 아래오 같이 두줄로 간략화
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

    """def get(self,*args,**kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args,**kwargs)
        else:
            return HttpResponseForbidden() #금지되어 있는 곳에 접근 했다는 것을 보여줌

    def post(self,*args,**kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().post(*args,**kwargs)
        else:
            return HttpResponseForbidden()"""

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style = "text-align : center; max-width : 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method = "post"><!--url 을 모두 일원화 하는 코드 본래는 accountapp/create
         accountapp 에 있는 create 로 연결하라는 의미-->
            {% csrf_token %}
            <!--{{form}}-->
            {% bootstrap_form form %}


            <input type="submit" class = "btn btn-dark rounded-pill col-6 mt-3 ">

        </form>
    </div>



{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}


{% block content %}

    <div style = "text-align : center; max-width : 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method = "post">
            {% csrf_token %}
            <input type="submit" class = "btn btn-danger rounded-pill col-6 mt-3 ">

        </form>
    </div>



{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div style="text-align:center; max-width: 500px; margin: 4rem auto;">
      <p>
        {{ target_user.date_joined }}
      </p>

      {% if target_user.profile %}
      <img src="{{ target_user.profile.image.url }}" alt=""
           style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
      <h2 style="font-family: 'NanumSquareB'">
        {{ target_user.profile.nickname }}
           {% if target_user == user %}
           <a class="material-icons"
              style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem"
                   href="{% url 'profileapp:update' pk=target_user.profile.pk %} ">
             edit
           </a>
        {% endif %}

      </h2>

      <h5 style="margin-bottom:3rem;">
        {{ target_user.profile.message }}
      </h5>

      {% else %}
        {% if target_user == user %}
        <a href="{% url 'profileapp:create' %}">
          <h2 style="font-family: 'NanumSquareB'">
            Create Profile

          </h2>
        </a>
        {% else %}
      <h2>
        닉네임 미설정
      </h2>
        {% endif %}
      {% endif %}




      {% if target_user == user %}
      <a class="material-icons"
              style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem"
              href="{% url 'accountapp:update' pk=user.pk %}">
          settings
      </a>
      <a class="material-icons"
              style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem"
              href="{% url 'accountapp:delete' pk=user.pk %}">

          cancel
      </a>
      {% endif %}
    </div>

    <div>
      {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>


  </div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


    <div style="text-align : center; max-width : 500px; margin: 4rem auto">
        <div>
            <h4>login</h4>
        </div>
        <div>
            <form action = "" method = "post">
                {% csrf_token %}
                <!--{{form}}-->
                {% bootstrap_form form %} <!--bootstrap_form 이 적용된 form 문이 적용되는 구문 -->
                <input type = "submit" class="btn btn-dark rounded-pill col-6 mt-3 ">


            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style = "text-align : center; max-width : 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method = "post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class = "btn btn-dark rounded-pill col-6 mt-3 ">

        </form>
    </div>



{% endblock %}